version: "3.5"

services:
  gunicorn:
    image: iss-prod:gunicorn
    container_name: plattform-django-gunicorn-prod
    build: ./django
    restart: unless-stopped
    expose:
      - 80
    volumes:
      - ./django:/usr/src/app
    network_mode: host
    logging:
      options:
        max-size: "200k"
        max-file: "10"
        

  
