version: '3.5'

services:

  postgres:
    image: postgres
    container_name: prod-postgresql
    network_mode: host
    environment:
      POSTGRES_USER: "issessions"
      POSTGRES_PASSWORD: "issessions"
      POSTGRES_DB: "iss"
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - ./data/:/var/lib/postgresql/data/pgdata

    
