version: '3.4'
services:
  django:
    image: iss-dev:django
    network_mode: host
    build: 
      context: ./django
    depends_on:
    - postgres
    - memcached
    container_name: django-dev
    volumes:
    - ./django:/usr/src/app

  postgres:
    image: iss-dev:postgres
    network_mode: host
    build:
      context: ./postgres
    container_name: postgresql

  memcached:
    image: iss-dev:memcached
    network_mode: host
    build:
      context: ./memcached
    container_name: memcached

