version: '3.4'


services:
  nginx:
    image: iss-dev:nginx
    build: ./nginx
    expose:
      - 80
    logging:
      options:
        max-size: "200k"
        max-file: "10"
    #ports:
    #  - ${APP_PORT}:80
    depends_on:
      - "gunicorn"
    logging:
      options:
        max-size: "200k"
        max-file: "10"
  gunicorn:
    image: iss-dev:gunicorn
    build: ./django
    depends_on:
    - postgres
    - memcached
    container_name: django-dev
    volumes:
    - ./django:/usr/src/app
#  django:
#    image: iss-dev:django
#    network_mode: host
#    build: 
#      context: ./django
#    depends_on:
#    - postgres
#    - memcached
#    container_name: django-dev
#    volumes:
#    - ./django:/usr/src/app
  postgres:
    image: iss-dev:postgres
    network_mode: host
    build:
      context: ./postgres
    container_name: postgresql

  memcached:
    image: iss-dev:memcached
    network_mode: host
    build:
      context: ./memcached
    container_name: memcached

