version: '3.4'
services:
  django:
    image: iss-dev:django
    #network_mode: host
    env_file:
    - enviroment.env
    ports:
    - 8000:8000
    build: 
      context: ./django
    depends_on:
    - postgres
    - memcached
    container_name: django
    volumes:
    - ./django:/usr/src/app
    networks:
    - iss
  
  postgres:
    image: iss-dev:postgres
    env_file:
    - enviroment.env
    # no need to expose postgresql to host @security
    #network_mode: host
    build:
      context: ./postgres
    container_name: postgresql
    networks:
    - iss

  memcached:
    image: iss-dev:memcached
    #network_mode: host
    # no need to expose memcached to host @security
    build:
      context: ./memcached
    container_name: memcached
    networks:
    - iss


networks:
  iss:
