version: "3.5"

services:
  gunicorn:
    image: iss-prod:scoreboard01
    env_file:
      - /scoreboard/env/environment.env
    container_name: iss_prod_scoreboard01
    build: ./django
    restart: unless-stopped
    expose:
      - 80
    ports:
      - 80:80
    volumes:
      - ./django:/usr/src/app
    logging:
      options:
        max-size: "200k"
        max-file: "10"
