CREATE DATABASE :DB_NAME;
CREATE USER :DB_USER;
/*ALTER USER :DB_USER WITH PASSWORD ':DB_PASS';
To fix
*/
ALTER USER :DB_USER WITH PASSWORD 'issessions'
ALTER ROLE :DB_USER with login;
ALTER ROLE :DB_USER with superuser;
